-- =====================================================
-- WORKSHEET: SaaS Analytics – Semantic & Business Views
-- PURPOSE:
--   Define business-ready metrics and views consumed
--   by Power BI dashboards
-- =====================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE SAAS_ANALYTICS;
USE SCHEMA VIEWS;

-- =====================================================
-- 1. CORE REVENUE & KPI VIEWS
-- =====================================================

CREATE OR REPLACE VIEW VW_REVENUE_KPIS AS
SELECT
    DATE_TRUNC('month', START_DATE) AS MONTH,
    COUNT(DISTINCT ACCOUNT_ID) AS ACTIVE_CUSTOMERS,
    SUM(MRR_AMOUNT) AS TOTAL_MRR,
    SUM(ARR_AMOUNT) AS TOTAL_ARR,
    AVG(MRR_AMOUNT) AS AVERAGE_MRR_PER_CUSTOMER,
    SUM(SUPPORT_TICKETS) AS TOTAL_SUPPORT_TICKETS
FROM ANALYTICS.FACT_SAAS_METRIC
GROUP BY 1
ORDER BY 1;

-- =====================================================
-- 2. CHURN & RETENTION ANALYSIS
-- =====================================================

CREATE OR REPLACE VIEW VW_CHURN_RATE AS
SELECT
    DATE_TRUNC('month', START_DATE) AS MONTH,
    COUNT(DISTINCT ACCOUNT_ID) AS TOTAL_ACCOUNTS,
    SUM(CHURNED_FLAG) AS CHURNED_ACCOUNTS,
    SUM(CHURNED_FLAG) / NULLIF(COUNT(DISTINCT ACCOUNT_ID),0) AS CHURN_RATE_PCT
FROM ANALYTICS.FACT_SAAS_METRIC
GROUP BY 1
ORDER BY 1;

CREATE OR REPLACE VIEW VW_RETENTION_COHORT AS
SELECT 
    DATE_TRUNC('month', START_DATE) AS COHORT_MONTH,
    DATE_TRUNC('month', END_DATE) AS CHURN_MONTH,
    COUNT(DISTINCT ACCOUNT_ID) AS CUSTOMERS
FROM ANALYTICS.FACT_SAAS_METRIC
GROUP BY 1,2
ORDER BY 1,2;

CREATE OR REPLACE VIEW VW_EARLY_CHURN AS
SELECT 
    COUNT(DISTINCT ce.ACCOUNT_ID) AS EARLY_CHURN_CUSTOMERS
FROM RAW.CHURN_EVENTS ce
JOIN ANALYTICS.DIM_SUBSCRIPTIONS s
    ON ce.ACCOUNT_ID = s.ACCOUNT_ID
WHERE DATEDIFF(day, s.START_DATE, ce.CHURN_DATE) <= 60;

-- =====================================================
-- 3. EXECUTIVE & SEGMENTATION VIEWS
-- =====================================================

CREATE OR REPLACE VIEW VW_EXECUTIVE_SUMMARY AS
SELECT 
    a.INDUSTRY,
    f.PLAN_TIER,
    COUNT(DISTINCT f.ACCOUNT_ID) AS CUSTOMERS,
    SUM(f.MRR_AMOUNT) AS TOTAL_MRR,
    SUM(f.ARR_AMOUNT) AS TOTAL_ARR,
    SUM(f.CHURNED_FLAG) AS CHURNED_CUSTOMERS,
    SUM(f.SUPPORT_TICKETS) AS TOTAL_SUPPORT_TICKETS
FROM ANALYTICS.FACT_SAAS_METRIC f
JOIN ANALYTICS.DIM_ACCOUNTS a
    ON f.ACCOUNT_ID = a.ACCOUNT_ID
GROUP BY a.INDUSTRY, f.PLAN_TIER;

CREATE OR REPLACE VIEW VW_CHURN_BY_PLAN AS
SELECT 
    PLAN_TIER,
    SUM(CHURNED_CUSTOMERS) AS CHURNED_CUSTOMERS,
    SUM(CUSTOMERS) AS TOTAL_CUSTOMERS,
    SUM(CHURNED_CUSTOMERS) / NULLIF(SUM(CUSTOMERS),0) AS CHURN_RATE
FROM VW_EXECUTIVE_SUMMARY
GROUP BY PLAN_TIER;

CREATE OR REPLACE VIEW VW_SUPPORT_VS_CHURN AS
SELECT
    r.MONTH,
    r.TOTAL_SUPPORT_TICKETS,
    r.ACTIVE_CUSTOMERS,
    r.TOTAL_SUPPORT_TICKETS / NULLIF(r.ACTIVE_CUSTOMERS,0) AS TICKETS_PER_CUSTOMER,
    c.CHURNED_ACCOUNTS
FROM VW_REVENUE_KPIS r
JOIN VW_CHURN_RATE c
    ON r.MONTH = c.MONTH;

-- =====================================================
-- 4. CUSTOMER HEALTH MODEL
-- =====================================================

CREATE OR REPLACE VIEW VW_CUSTOMER_BASE_METRICS AS
SELECT
    f.ACCOUNT_ID,
    AVG(f.MRR_AMOUNT) AS AVG_MRR,
    SUM(f.TOTAL_USAGE_EVENTS) AS TOTAL_USAGE,
    SUM(f.TOTAL_FEATURE_USAGE) AS FEATURE_USAGE,
    SUM(f.SUPPORT_TICKETS) AS SUPPORT_TICKETS,
    SUM(f.TOTAL_ERRORS) AS TOTAL_ERRORS,
    DATEDIFF(day, MIN(s.START_DATE), CURRENT_DATE()) AS TENURE_DAYS,
    MAX(f.CHURNED_FLAG) AS IS_CHURNED
FROM ANALYTICS.FACT_SAAS_METRIC f
JOIN ANALYTICS.DIM_SUBSCRIPTIONS s
    ON f.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID
GROUP BY f.ACCOUNT_ID;

CREATE OR REPLACE VIEW VW_CUSTOMER_HEALTH AS
WITH stats AS (
    SELECT
        *,
        MAX(TOTAL_USAGE) OVER() AS MAX_USAGE,
        MAX(FEATURE_USAGE) OVER() AS MAX_FEATURE,
        MAX(SUPPORT_TICKETS) OVER() AS MAX_TICKETS,
        MAX(TOTAL_ERRORS) OVER() AS MAX_ERRORS,
        MAX(TENURE_DAYS) OVER() AS MAX_TENURE
    FROM VW_CUSTOMER_BASE_METRICS
)
SELECT
    ACCOUNT_ID,
    AVG_MRR,
    TOTAL_USAGE,
    FEATURE_USAGE,
    SUPPORT_TICKETS,
    TOTAL_ERRORS,
    TENURE_DAYS,
    IS_CHURNED,

    (TOTAL_USAGE / NULLIF(MAX_USAGE,1)) * 100 AS USAGE_SCORE,
    (FEATURE_USAGE / NULLIF(MAX_FEATURE,1)) * 100 AS FEATURE_SCORE,
    (1 - SUPPORT_TICKETS / NULLIF(MAX_TICKETS,1)) * 100 AS SUPPORT_SCORE,
    (1 - TOTAL_ERRORS / NULLIF(MAX_ERRORS,1)) * 100 AS ERROR_SCORE,
    (TENURE_DAYS / NULLIF(MAX_TENURE,1)) * 100 AS TENURE_SCORE,

    (
        0.30 * (TOTAL_USAGE / NULLIF(MAX_USAGE,1)) * 100 +
        0.25 * (FEATURE_USAGE / NULLIF(MAX_FEATURE,1)) * 100 +
        0.20 * (1 - SUPPORT_TICKETS / NULLIF(MAX_TICKETS,1)) * 100 +
        0.15 * (1 - TOTAL_ERRORS / NULLIF(MAX_ERRORS,1)) * 100 +
        0.10 * (TENURE_DAYS / NULLIF(MAX_TENURE,1)) * 100
    ) AS HEALTH_SCORE,

    CASE
        WHEN HEALTH_SCORE < 30 THEN 'Critical'
        WHEN HEALTH_SCORE < 50 THEN 'At Risk'
        WHEN HEALTH_SCORE < 75 THEN 'Healthy'
        ELSE 'Champion'
    END AS HEALTH_SEGMENT
FROM stats;

-- =====================================================
-- 5. REVENUE WATERFALL (MRR MOVEMENT)
-- =====================================================

CREATE OR REPLACE VIEW VW_MRR_WATERFALL AS
WITH base AS (
    SELECT
        DATE_TRUNC('month', START_DATE) AS MONTH,
        ACCOUNT_ID,
        SUM(MRR_AMOUNT) AS MRR
    FROM ANALYTICS.FACT_SAAS_METRIC
    GROUP BY 1,2
),
lagged AS (
    SELECT
        MONTH,
        ACCOUNT_ID,
        MRR,
        LAG(MRR) OVER (PARTITION BY ACCOUNT_ID ORDER BY MONTH) AS PREV_MRR
    FROM base
),
classified AS (
    SELECT
        MONTH,
        CASE
            WHEN PREV_MRR IS NULL AND MRR > 0 THEN 'New'
            WHEN MRR > PREV_MRR THEN 'Expansion'
            WHEN MRR < PREV_MRR AND MRR > 0 THEN 'Contraction'
            WHEN MRR = 0 OR MRR IS NULL THEN 'Churn'
            ELSE 'Flat'
        END AS MOVEMENT_TYPE,
        CASE
            WHEN PREV_MRR IS NULL AND MRR > 0 THEN 1
            WHEN MRR > PREV_MRR THEN 2
            WHEN MRR < PREV_MRR AND MRR > 0 THEN 3
            WHEN MRR = 0 OR MRR IS NULL THEN 4
        END AS MOVEMENT_ORDER,
        (MRR - COALESCE(PREV_MRR,0)) AS MRR_AMOUNT
    FROM lagged
)
SELECT
    MONTH,
    MOVEMENT_TYPE,
    MOVEMENT_ORDER,
    SUM(MRR_AMOUNT) AS MRR_AMOUNT
FROM classified
WHERE MOVEMENT_TYPE <> 'Flat'
GROUP BY 1,2,3;
