-- =====================================================
-- WORKSHEET: SaaS Analytics – Star Schema
-- PURPOSE:
--   Transform raw SaaS data into analytics-ready
--   star schema (dimensions + fact)
-- =====================================================

USE SCHEMA SAAS_ANALYTICS.ANALYTICS;

-- -------------------------
-- DIM_ACCOUNTS
-- -------------------------
CREATE OR REPLACE TABLE DIM_ACCOUNTS AS
SELECT
    ACCOUNT_ID,
    ACCOUNT_NAME,
    INDUSTRY,
    COUNTRY,
    REFERRAL_SOURCE,
    SIGNUP_DATE,
    SEATS,
    IS_TRIAL
FROM SAAS_ANALYTICS.RAW.ACCOUNTS;

-- -------------------------
-- DIM_SUBSCRIPTIONS
-- -------------------------
CREATE OR REPLACE TABLE DIM_SUBSCRIPTIONS AS
SELECT
    SUBSCRIPTION_ID,
    ACCOUNT_ID,
    PLAN_TIER,
    BILLING_FREQUENCY,
    SEATS,
    IS_TRIAL,
    START_DATE,
    END_DATE
FROM SAAS_ANALYTICS.RAW.SUBSCRIPTIONS;

-- -------------------------
-- DIM_COUNTRY
-- -------------------------
CREATE OR REPLACE TABLE DIM_COUNTRY AS
SELECT DISTINCT
    COUNTRY,
    CASE 
        WHEN COUNTRY IN ('US','CA') THEN 'North America'
        WHEN COUNTRY IN ('IN','SG') THEN 'Asia'
        WHEN COUNTRY IN ('GB','DE','FR') THEN 'Europe'
        ELSE 'Other'
    END AS REGION
FROM SAAS_ANALYTICS.RAW.ACCOUNTS;

-- -------------------------
-- DIM_PLAN
-- -------------------------
CREATE OR REPLACE TABLE DIM_PLAN AS
SELECT DISTINCT
    PLAN_TIER,
    BILLING_FREQUENCY
FROM SAAS_ANALYTICS.RAW.SUBSCRIPTIONS;

-- -------------------------
-- DIM_DATE
-- -------------------------
CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    DATE_VALUE,
    YEAR(DATE_VALUE) AS YEAR,
    MONTH(DATE_VALUE) AS MONTH,
    TO_CHAR(DATE_VALUE, 'YYYY-MM') AS YEAR_MONTH
FROM (
    SELECT SIGNUP_DATE AS DATE_VALUE FROM SAAS_ANALYTICS.RAW.ACCOUNTS
    UNION
    SELECT START_DATE FROM SAAS_ANALYTICS.RAW.SUBSCRIPTIONS
    UNION 
    SELECT USAGE_DATE FROM SAAS_ANALYTICS.RAW.FEATURE_USAGE
    UNION
    SELECT CHURN_DATE FROM SAAS_ANALYTICS.RAW.CHURN_EVENTS
);

-- -------------------------
-- FACT_SAAS_METRIC
-- Grain: Subscription x Month
-- -------------------------
CREATE OR REPLACE TABLE FACT_SAAS_METRIC AS
SELECT 
    s.SUBSCRIPTION_ID,
    s.ACCOUNT_ID,
    s.PLAN_TIER,
    s.BILLING_FREQUENCY,
    s.MRR_AMOUNT,
    s.ARR_AMOUNT,
    s.START_DATE,
    s.END_DATE,

    COUNT(f.USAGE_ID) AS TOTAL_USAGE_EVENTS,
    SUM(f.USAGE_COUNT) AS TOTAL_FEATURE_USAGE,
    SUM(f.ERROR_COUNT) AS TOTAL_ERRORS,
    COUNT(DISTINCT t.TICKET_ID) AS SUPPORT_TICKETS,

    MAX(CASE WHEN c.ACCOUNT_ID IS NOT NULL THEN 1 ELSE 0 END) AS CHURNED_FLAG

FROM SAAS_ANALYTICS.RAW.SUBSCRIPTIONS s
LEFT JOIN SAAS_ANALYTICS.RAW.FEATURE_USAGE f
    ON s.SUBSCRIPTION_ID = f.SUBSCRIPTION_ID
LEFT JOIN SAAS_ANALYTICS.RAW.SUPPORT_TICKETS t
    ON s.ACCOUNT_ID = t.ACCOUNT_ID
LEFT JOIN SAAS_ANALYTICS.RAW.CHURN_EVENTS c
    ON s.ACCOUNT_ID = c.ACCOUNT_ID

GROUP BY
    s.SUBSCRIPTION_ID,
    s.ACCOUNT_ID,
    s.PLAN_TIER,
    s.BILLING_FREQUENCY,
    s.MRR_AMOUNT,
    s.ARR_AMOUNT,
    s.START_DATE,
    s.END_DATE;
